version: "3.7"
services:
  ski-api:
    image: sindachamakh/ski-image:latest
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3308:3308

    environment:
      MYSQL_DATABASE: skiProject
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
